const olColor = {
  "color-default": "#eee", 
  "color-primary": "#4d79f6",
  "color-primary-hover": "#255df7",
  "color-secondary": "#4ac7ec",
  "color-secondary-hover": "#0ebaee",
  "color-success": "#1ecab8",
  "color-success-hover": "#57c7d4",
  "color-warning": "#f3c74d",
  "color-warning-hover": "#f1b308",
  "color-info": "#9ba7ca",
  "color-info-hover": "#8b9ac7",
  "color-danger": "#f1646c",
  "color-danger-hover": "#f54952",
  "color-dark": "#2f4686",
  "color-dark-hover": "#292929",
  "color-light": "#f1f5fa",
  "color-light-hover": "#f1f5fa",
  "color-link": "#8997bd",
  "color-link-hover": "#8997bd",
  "color-pink": "#ff5da0",
  "color-pink-hover": "#ff5da0",
  "color-purple": "#7551e9",
  "color-purple-hover": "#7551e9",
  "color-white": "#fff",
  "color-white-hover": "#fff",
  "color-muted": "#a4abc5",
  "color-muted-hover": "#a4abc5",
  "color-style": ['primary', 'danger', 'success', 'info', 'warning', 'dark', "pink", "purple", "muted", "link", 'white', 'light']
}

module.exports = {olColor}